FROM node:14-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

ENV WDS_SOCKET_PORT=0

COPY --chown=node:node ./package.json ./

RUN npm install

COPY --chown=node:node ./ ./

CMD ["npm", "start"]

EXPOSE 3000